name: OpenCup
version: '${version}'

main: org.kerix.openhost.opencup.boostrap.Main
bootstrapper: org.kerix.openhost.opencup.MainBootstrap
loader: org.kerix.openhost.opencup.MainLoader
api-version: '1.21.1'
load: POSTWORLD

authors: [ Kerix ]

permissions:
  opencup.admin:
    description: Grants access to OpenCup admin commands (/opencup start, skip, end, addpoints)
    default: op
